version: "3.5"
services:
    db:
      container_name: eudb
      image: mysql:latest
      ports:
       - "3307:3306"  
      environment:
         - MYSQL_ROOT_PASSWORD=mysql
         - MYSQL_DATABASE=eutravel
         - MYSQL_USER=admin
         - MYSQL_PASSWORD=password

      volumes:
         - /home/achim/Dokumente/mysql/data:/var/lib/mysql
         - /home/achim/Dokumente/mysql/init:/docker-entrypoint-initdb.d/:ro
    #service 2: definition of phpMyAdmin
    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      container_name: my-php-myadmin
      ports:
        - "8082:80"
      restart: always
        
      depends_on:
        - db
      environment:
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: mysql