version: "3.5"
services:
    db:
      container_name: eudb
      image: mysql:latest
      networks:
      - eutravel-mysql
      ports:
       - "3307:3306"  
      environment:
         - MYSQL_ROOT_PASSWORD=mysql
         - MYSQL_DATABASE=eutravel
         - MYSQL_USER=admin
         - MYSQL_PASSWORD=password

      volumes:
         - /home/achim/Dokumente/mysql/data:/var/lib/mysql
         - /home/achim/Dokumente/mysql/init:/docker-entrypoint-initdb.d/:ro
    #service 2: definition of phpMyAdmin
    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      container_name: my-php-myadmin
      networks:
      - eutravel-mysql
      ports:
        - "8082:80"
      restart: always
        
      depends_on:
        - db
      environment:
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: mysql

    #service 3: definition of springboot eurtravel
    customerservice:                        #it is just a name, which will be used only in this file.
      image: eutravel-service               #name of the image after dockerfile executes
      container_name: eutravel-service-app  #name of the container created from docker image
      build:
        context: .                          #docker file path (. means root directory)
        dockerfile: eutravel2.dockerfile    #docker file name
      networks:
      - eutravel-mysql
      ports:
        - "8084:8084"                       #docker containter port with your os port
      restart: always
        
      depends_on:                           #define dependencies of this app
        - db                                #dependency name (which is defined with this name 'db' in this file earlier)
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://eudb/eutravel
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: mysql
        
    #service 4: definition of angular client for eurtravel
    clientapp:
      image: eutravel-client
      container_name: eutravel-client-app
      build:
        context: .
        dockerfile: client-app.dockerfile
      networks:
      - eutravel-mysql
      ports:
        - "4200:80"
      restart: always
      depends_on:
        - customerservice        

networks:
  eutravel-mysql: 
    driver: bridge